Autogenerated tree updates.
merged:

  gentoo-staging: 9292583023a6610905c79a4707db3ac6c63b3a31
  gentoo-staging-nov-2021: a15a64f48741a493e49dfee7d4280a3dc10cd21d
  kit-fixups: 4a37ed331bd9ad9da5b9941a303b6490930b3174

diff --git a/media-gfx/exiv2/templates/exiv2.tmpl b/media-gfx/exiv2/templates/exiv2.tmpl
--- a/media-gfx/exiv2/templates/exiv2.tmpl
+++ b/media-gfx/exiv2/templates/exiv2.tmpl
@@ -2,20 +2,22 @@
 
 EAPI=7
 
-SRC_URI="https://github.com/Exiv2/exiv2/releases/download/v${PV}/${P}-Source.tar.gz"
-KEYWORDS="next"
-S="${WORKDIR}/${P}-Source"
 
 CMAKE_ECLASS=cmake
 PYTHON_COMPAT=( python3+ )
-inherit cmake-multilib python-any-r1
+inherit cmake python-any-r1
 
-DESCRIPTION="EXIF, IPTC and XMP metadata C++ library and command line utility"
-HOMEPAGE="https://www.exiv2.org/"
+DESCRIPTION="{{desc}}"
+HOMEPAGE="{{homepage}}"
+SRC_URI="{{src_uri}}"
+LICENSE="{{license}}"
 
-LICENSE="GPL-2"
-SLOT="0/27"
-IUSE="+bmff doc examples nls +png webready +xmp"
+S="${WORKDIR}/{{github_user}}-{{github_repo}}-{{sha[:7]}}"
+
+SLOT="0/$(ver_cut 1-2)"
+KEYWORDS="*"
+IUSE="+bmff doc examples nls +png test webready +xmp"
+RESTRICT="!test? ( test )"
 
 BDEPEND="
 	doc? (
@@ -26,18 +28,20 @@ BDEPEND="
 		virtual/pkgconfig
 	)
 	nls? ( sys-devel/gettext )
+	dev-libs/inih
 "
 RDEPEND="
-	virtual/libiconv[${MULTILIB_USEDEP}]
-	nls? ( virtual/libintl[${MULTILIB_USEDEP}] )
-	png? ( sys-libs/zlib[${MULTILIB_USEDEP}] )
+    >=virtual/libiconv-0-r1
+	nls? ( >=virtual/libintl-0-r1 )
+	png? ( sys-libs/zlib )
 	webready? (
-		net-libs/libssh[sftp,${MULTILIB_USEDEP}]
-		net-misc/curl[${MULTILIB_USEDEP}]
+		>net-libs/libssh-0.9.1[sftp]
+		net-misc/curl
 	)
-	xmp? ( dev-libs/expat[${MULTILIB_USEDEP}] )
+	xmp? ( dev-libs/expat )
 "
-DEPEND="${DEPEND}"
+DEPEND="${DEPEND}
+	test? ( dev-cpp/gtest )"
 
 DOCS=( README.md doc/ChangeLog doc/cmd.txt )
 
@@ -56,34 +60,37 @@ src_prepare() {
 	sed -e "/^include.*compilerFlags/s/^/#DONT /" -i CMakeLists.txt || die
 }
 
-multilib_src_configure() {
+src_configure() {
 	local mycmakeargs=(
 		-DCMAKE_CXX_STANDARD=14
 		-DEXIV2_BUILD_SAMPLES=NO
 		-DEXIV2_ENABLE_NLS=$(usex nls)
 		-DEXIV2_ENABLE_PNG=$(usex png)
 		-DEXIV2_ENABLE_CURL=$(usex webready)
-		-DEXIV2_ENABLE_SSH=$(usex webready)
 		-DEXIV2_ENABLE_WEBREADY=$(usex webready)
 		-DEXIV2_ENABLE_XMP=$(usex xmp)
 		-DEXIV2_ENABLE_BMFF=$(usex bmff)
-		$(multilib_is_native_abi || echo -DEXIV2_BUILD_EXIV2_COMMAND=NO)
-		$(multilib_is_native_abi && echo -DEXIV2_BUILD_DOC=$(usex doc))
+		$(echo -DEXIV2_BUILD_EXIV2_COMMAND=NO)
+		$(echo -DEXIV2_BUILD_DOC=$(usex doc))
+		$(echo -DEXIV2_BUILD_UNIT_TESTS=$(usex test))
 		-DCMAKE_INSTALL_DOCDIR="${EPREFIX}"/usr/share/doc/${PF}/html
 	)
 
 	cmake_src_configure
 }
 
-multilib_src_compile() {
+src_compile() {
 	cmake_src_compile
 
-	if multilib_is_native_abi; then
-		use doc && eninja doc
-	fi
+	use doc && eninja doc
 }
 
-multilib_src_install_all() {
+src_test() {
+	cd "${BUILD_DIR}"/bin || die
+	./unit_tests || die "Failed to run tests"
+}
+
+src_install() {
 	use xmp && DOCS+=( doc/{COPYING-XMPSDK,README-XMP,cmdxmp.txt} )
 
 	einstalldocs
